#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

STDIN=$(cat)
APP="$1"
NAME_FILE="NAME"
NAME_FILE_PATH="$DOKKU_ROOT/$APP/$NAME_FILE"

output=""
if [[ -f "$NAME_FILE_PATH" ]]; then
  # issue a cleanup, removes old named docker containers
  dokku cleanup
  # need to wait, docker doesn't appear to do this immediately
  sleep 2
  COUNT=$(wc -w $NAME_FILE_PATH)
  if [[ "$COUNT" -ne "1" ]]; then
    dokku_log_warn "NAME file does not contain exactly one word"
  else
    while read line
    do
      output="$output --name=$line"
    done < $NAME_FILE_PATH
  fi
fi
echo "$STDIN$output"
